spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rate-limiter
    security:
      filter:
        order: 10
    cache:
      cache-names:
        - rate-limit-buckets
      caffeine:
        spec: maximumSize=100000,expireAfterAccess=3600s

jwt:
  secretKey: thisisatestoftheemergencybroadcastsystem